input: $input
output: $output
datadir: $datadir
batchsize: $batch_size
options:
  overwrite: false
  maxcores: $max_cores
  progress: true

resources:
  get_gfw_treecover:
    args:
      version: GFC-2023-v1.11
  get_gfw_lossyear:
    args:
      version: GFC-2023-v1.11
  get_biodiversity_intactness_index:
    args:
      path: $raw/lbii.asc
  get_teow:
  get_irr_carbon:
  get_vul_carbon:
  get_man_carbon:
  get_humanfootprint:
    args:
      years: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  get_worldpop:
    args:
      years: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  get_iucn:
    args:
      paths:
        - $raw/Amphibians_SR_2023.tif
        - $raw/Amphibians_THR_SR_2023.tif
        - $raw/Birds_SR_2023.tif
        - $raw/Birds_THR_SR_2023.tif
        - $raw/Combined_SR_2023.tif
        - $raw/Combined_THR_SR_2023.tif
        - $raw/Mammals_SR_2023.tif
        - $raw/Mammals_THR_SR_2023.tif
        - $raw/Reptiles_SR_2023.tif
        - $raw/Reptiles_THR_SR_2023.tif
  get_key_biodiversity_areas:
    args:
      path: $raw/kbas.gpkg
  get_gmw:
    args:
      years: [2015, 2016, 2017, 2018, 2019, 2020]
  get_ipbes_biomes:
  #get_mcd64a1:
  #  args:
  #    years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
  #  options:
  #    maxcores: 4
  get_esalandcover:
    args:
      years: [2015, 2016, 2017, 2018, 2019]

indicators:
  calc_mangroves_area:
    options:
      chunksize: 5000000
  calc_ipbes_biomes:
    options:
      chunksize: 5000000
  #calc_burned_area:
  #  args:
  #    engine: exactextract
  #  options:
  #    chunksize: 500000
  calc_landcover:
    options:
      chunksize: 500000
  calc_treecover_area:
    args:
      years: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
      min_cover: 30
      min_size: 1
    options:
      chunksize: 50000
  calc_biodiversity_intactness_index:
    options:
      chunksize: 50000
  calc_biome:
    options:
      chunksize: 5000000
  calc_irr_carbon:
    args:
      type: all
      engine: exactextract
      stats: [min, mean, median, sd, max, sum]
    options:
      chunksize: 500000
  calc_vul_carbon:
    args:
      type: all
      engine: exactextract
      stats: [min, mean, median, sd, max, sum]
    options:
      chunksize: 500000
  calc_man_carbon:
    args:
      type: all
      engine: exactextract
      stats: [min, mean, median, sd, max, sum]
    options:
      chunksize: 500000
  calc_humanfootprint:
    args:
      stats: [min, mean, median, sd, max, sum]
      engine: exactextract
    options:
      chunksize: 50000
  calc_species_richness:
    args:
      stats: [min, mean, median, sd, max, sum]
      engine: exactextract
  calc_key_biodiversity_area:
    options:
      chunksize: 5000000
  calc_population_count:
    args:
      stats: [min, mean, median, sd, max, sum]
      engine: exactextract
    options:
      chunksize: 500000
